name: Fusion Film House
favicon: null
layout_spectrum: 0.73786
typography_spectrum: 0.35283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#132406'
    - '#f3c5b0'
    - '#8b7b28'
    - '#a64b83'
    - '#fdf7e9'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
