name: Fusion Film House
favicon: null
layout_spectrum: 0.73786
typography_spectrum: 0.35283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1f21'
    - '#6f7876'
    - '#c3c8c7'
    - '#efefee'
    - '#4a5053'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
